### PR TITLE
A few tweaks

### PR DESCRIPTION
**Pull request by HSstudent16**
Greetings, ski!

Here's what you get for asking me to look through your code :p
I've added a few small changes that will hopefully make ski.js easier to embed in a webpage:

- The key event listeners are now added to the canvas, not the entire document, in case a programmer needs those for other purposes.
- Event listeners are added or removed when a program switches canvas via `set()`
- A `project()` method has been added to the Vector class
- `getImage()` and `getFont()` rely on `loadImage()` and `loadFont()`, respectively.

The minified files should be updated, too :D

### CODE REVIEW

**Comment by thelegendski** [comment]
heyo, :D!

fixed a quick bug with the event listeners where you forgot to remove a conditional.

i have a script called `defer.js` that defers gettin' the canvas element. is there a way i could incorporate that into the main script? `defer.js` allows other canvases to exist in the body, so i can take the first canvas element an' get the WebGL context which i wouldn't have been able to do with `main.js`.
the rest looks great, :D! thanks for your help, :).

**Comment by HSstudent16** [comment]
Oops :P
What line is that delinquent conditional on?

Hmm... the only Ideas I have are requiring ski.js to be initialized (e.g. with `set(canvasEl)`) or ignoring tags with a `data-defer` attribute.

**Comment by thelegendski** [comment]
lol, i say there's a bug, but then don't say what it is.
`if(e.target instanceof HTMLBodyElement)`

which do you think is better for user experience?

**Comment by HSstudent16** [comment]
This is why I have not touched ACME in months :)

Yup, on it!

**Comment by HSstudent16** [comment]
Okay, that should do it!

**Comment by thelegendski** [comment]
hooray, :D! merged! should be good to go, :).

**Pull request merged**
